pygments: true
permalink: pretty
server_port: 3000
markdown: kramdown

paginate: 5

exclude: ['Rakefile', 'README.markdown']

photos: http://dl.dropbox.com/u/3234860/andyfreeland.net/photo
#photos: /photo
